---
dependencies:

galaxy_info:
  author: virhi
  description: Symfony for Debian/Ubuntu.
  license: "license (MIT)"
  min_ansible_version: 1.4
  platforms:
  - name: Debian
    versions:
    - all
  - name: Ubuntu
    versions:
    - precise
    - raring
    - saucy
    - trusty
  categories:
    - web